name: Flutter CI
on: [push, pull_request]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Format & Analyze
        run: |
          flutter format --set-exit-if-changed .
          flutter analyze
      - name: Run tests
        run: flutter test
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses
      - name: Build APK
        run: flutter build apk --release

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Enable Web
        run: flutter config --enable-web
      - name: Format & Analyze
        run: |
          flutter format --set-exit-if-changed .
          flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build Web
        run: flutter build web --release --base-href="/${{ github.event.repository.name }}/"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web